sudo: false
language: python
services:
- docker
before_install:
- docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq
  nameko/nameko-rabbitmq:3.6.6
cache: pip
python:
- '3.6'
install:
- pip install tox-travis virtualenv tox python-coveralls
script:
- QUIET=true tox
stages:
- test
- deploy
jobs:
  include:
  - stage: test
    python:
    - '2.7'
    - '3.6'
    - '3.7'
    script:
    - QUIET=true tox
  - stage: deploy
    script: skip
    install: skip
    on:
      repo: Yupeek/nameko-serializer
      tags: true
    deploy:
      provider: pypi
      user: yupeek
      password:
        secure: Qz4iVVth1xdwfLQZZe13dFeibKF+fzSM2UMlwxzgiII3O8xTQXA6pjL76HOWEaFLafYt1RokQttCq2RxgHm3BS4uUWfPUtSXcx4CQND09YcnKMvXnrehP5tpjAW61yGqNLHGWBOzY81+jHl8TMdU76e5CsX3V0h+nQVXu1bh4vzF9Z0CqwqOWtOO37Ocfu/qZzwi4ytuKcsyntMXCJplBGrGHEFjhW8s0fjWJgrtjLtQKR7b8unR+mZNf7TN7iqg9Atyoy+IhHh/SWH/Tu7EKHk159u86imnzwKwYSkiCp3r8f0kp/KfEPYc1B6s4fVRR6F8D05sMmkXBOtJw5ROZUz1hEgLLCW/Xj4bTyin1HSp/s0WLs2b0m2jP3dQ+LFulXOw4/1aCRF2LDV/i+EjOC0bDmBHOokmjq6o82jCOtAJeJsH4sGFGgwHUloLbO8PT3vjy4o+SglC8PI35dhpOFadmZXBY55eVIjxrwRYqEYBXbVhiArnOSin1mMunxZOWx/w6IHYcoCA4N3wQVrlAKkjgooCwudMY6sVxPMl7YJz6JNi9QSmmUhKx2VjnbVjcJs+koaK7cJs8c8XqXPShqCROWne7qg1REU0kdCsVfxxKC7gOC/yRELDLPqMbhw9TNOMjRMH3zat/8D/JmIqOd/iylZZ34DUaRDCo1GWqDk=
      distributions: sdist bdist_wheel
      skip_existing: true

