sudo: false
language: python

services:
- docker


before_install:
- docker run -d --rm -p 15672:15672 -p 5672:5672 -p 5671:5671 --name nameko-rabbitmq nameko/nameko-rabbitmq:3.6.6

cache: pip

python:
- '2.7'
- '3.5'
- '3.6'
install:
- pip install tox-travis virtualenv tox python-coveralls

script:
- QUIET=true tox

stages:
- tox
- deploy

jobs:
  include:
  # deploy if master and tag
  - stage: tox
    script:
    - QUIET=true tox

  - stage: deploy
    script: skip # to not run Travis' default script
    install: skip
    on:
      repo: Yupeek/nameko-serializer
      tags: true
    deploy:
      provider: pypi
      user: yupeek

      password:
        secure: e24svC/SHS9PcbgTqv40QXsiziygb9KgYqz6pjwI5eIM05s5a9kuF7OadV+Kd2Gq/XlxpPn9wKomYUoBLwg1eZs4kpAo8qDMZp51xi9hR8gYHmmOzvmV2NTfSdeEKEGHNbSNid3GUOZiKm3IDw3ym7983kkLLVsdRlty8b/X8kqPH+m+M+1lXl7d5l4rH3+rov8udasBGX4h3x8qdI1YKZfiL33gW632Fr5rrkC3ISTX5ClI8SgDZHdc3uG8C6u9TLTwjcxrAtTvIBHIg8BX4i8HR0o8LdyfHARqZbk6g2N6sK5B1kIgXumiY2gA9g5cnz/TEC+ZJkn2AueEHJkpY5gyJnmiC67ro3v0h3Gkl3v4H7k3GhbmZiMjA3Vzt6Ea/hBCNk7YfBo22j8h65F8KuS24OiQjxPO+UFI6bzYnAvP6HQdiM9M3Wai7Szv+GYRLRqZt5psxEtg9pvqZLLmr6LW+kvFjYG1bYVGNZG2Lr0VLQ99PVfV+LwV74XpWAUBLFsGuTAEdIuWUln0zeXwLRh/FQXhthVc1/A9uEviBVT9yaiYG8KvRd43b5NGlaXsPjH4bkj3xVpEBE5OhO64C33sNBABI0xbaFzLQgbrH4FP1MPhzxxK4p5GiXa1w+WfPtF/gFYfBGjP7NtDkKhFAS/UZ/WoPgRWQXkBtqWBnw8=

      distributions: sdist bdist_wheel
      skip_existing: true
